SET search_path TO mh_staging;

show search_path;

---Creating ppd table
CREATE TABLE IF NOT EXISTS "secondary-data".ppd_data 
( 
ssid VARCHAR,
pid VARCHAR,
sid_sd VARCHAR,
age REAL,
mrtl VARCHAR,
edc VARCHAR,
ocp1 VARCHAR,
ocp2 VARCHAR,
rlg VARCHAR,
hsld INT,
incm VARCHAR,
rltp VARCHAR,
mstr VARCHAR,
fstr VARCHAR,
estr VARCHAR,
sstr VARCHAR,
nstr VARCHAR,
hist1 VARCHAR,
hist2 VARCHAR,
pg INT,
dlv INT,
msc INT,
sbth INT,
indab INT,
gst INT,
uppg VARCHAR,
attd VARCHAR,
alch1 VARCHAR,
alch2 VARCHAR,
mntl VARCHAR,
fmntl VARCHAR,
otrlg VARCHAR,
shist1 VARCHAR,
mnpr VARCHAR,
sfmntl VARCHAR,
spocp1 VARCHAR,
spbsn1 VARCHAR,
spocp2 VARCHAR,
spbsn2 VARCHAR,
oocp1 VARCHAR,
sid_prf VARCHAR,
mod VARCHAR,
bcmp VARCHAR,
pwp VARCHAR,
lbw VARCHAR,
nad VARCHAR,
otcm VARCHAR,
bhp VARCHAR,
sex VARCHAR,
hppy1 VARCHAR,
hppy2 VARCHAR,
fbr VARCHAR,
noc INT,
sic VARCHAR,
cnfl VARCHAR,
fdlt VARCHAR,
hlp VARCHAR,
ckn VARCHAR,
clng VARCHAR,
ccr VARCHAR,
sbcmp VARCHAR,
snad VARCHAR,
ssic VARCHAR,
ohlp2 VARCHAR,
slbw VARCHAR,
sotcm VARCHAR,
id_epds1 VARCHAR,
init1 VARCHAR NULL,
addr1 VARCHAR NULL,
phn1 VARCHAR NULL,
lgh1 VARCHAR,
enjy1 VARCHAR,
blmd1 VARCHAR,
anxs1 VARCHAR,
scrd1 VARCHAR,
sad1 VARCHAR,
thng1 VARCHAR,
cryn1 VARCHAR,
slpn1 VARCHAR,
hrmg1 VARCHAR,
admin1 VARCHAR NULL,
scr1 INT,
sid_pp VARCHAR,
tym_pp VARCHAR,
impt VARCHAR,
why VARCHAR,
opn VARCHAR,
id2 VARCHAR,
init2 VARCHAR NULL,
addr2 VARCHAR NULL,
phn2 VARCHAR NULL,
lgh2 VARCHAR,
enjy2 VARCHAR,
blmd2 VARCHAR,
anxs2 VARCHAR,
scrd2 VARCHAR,
sad2 VARCHAR,
thng2 VARCHAR,
cryn2 VARCHAR,
slpn2 VARCHAR,
hrmg2 VARCHAR,
admin2 VARCHAR NULL,
scr2 INT,
dtsd VARCHAR,
dtpnrf VARCHAR,
ydob1 VARCHAR,
bdob1 VARCHAR,
dtepds1 VARCHAR,
ydob2 VARCHAR,
bdob2 VARCHAR,
dt2 VARCHAR
)

SELECT * FROM "secondary-data".ppd_data;

--DROP TABLE IF EXISTS "secondary-data".ppd_data;